service: test1

app: test1-app
org: matthewb487

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  # you can overwrite defaults here
  # stage: dev
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: first-endpoint
          method: GET

plugins:
  - serverless-plugin-typescript
  - serverless-mocha-plugin
